// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace Valve.VR
{
    using System;
    using UnityEngine;
    
    
    public class SteamVR_Input_ActionSet_Buttons_Input_In : Valve.VR.SteamVR_Action_List
    {
        
        public Valve.VR.SteamVR_Action_Boolean leftTrigger;
        
        public Valve.VR.SteamVR_Action_Boolean rightTrigger;
        
        public Valve.VR.SteamVR_Action_Boolean leftMenuButton;
        
        public Valve.VR.SteamVR_Action_Boolean rightMenuButton;
        
        public Valve.VR.SteamVR_Action_Boolean leftDpad;
        
        public Valve.VR.SteamVR_Action_Boolean rightDpad;
        
        public Valve.VR.SteamVR_Action_Boolean leftSystemButton;
        
        public Valve.VR.SteamVR_Action_Boolean rightSystemButton;
        
        public Valve.VR.SteamVR_Action_Boolean leftGrip;
        
        public Valve.VR.SteamVR_Action_Boolean rightGrip;
    }
}
