// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace Valve.VR
{
    using System;
    using UnityEngine;
    
    
    public class SteamVR_Input_ActionSet_Buttons_Input_In : Valve.VR.SteamVR_Action_List
    {
        
        public Valve.VR.SteamVR_Action_Boolean leftTrigger;
        
        public Valve.VR.SteamVR_Action_Boolean rightTrigger;
        
        public Valve.VR.SteamVR_Action_Boolean leftMenuButton;
        
        public Valve.VR.SteamVR_Action_Boolean rightMenuButton;
        
        public Valve.VR.SteamVR_Action_Boolean leftDpadClick;
        
        public Valve.VR.SteamVR_Action_Boolean rightDpadClick;
        
        public Valve.VR.SteamVR_Action_Boolean leftGrip;
        
        public Valve.VR.SteamVR_Action_Boolean rightGrip;
        
        public Valve.VR.SteamVR_Action_Skeleton leftController;
        
        public Valve.VR.SteamVR_Action_Skeleton rightController;
        
        public Valve.VR.SteamVR_Action_Single leftTriggerAnalog;
        
        public Valve.VR.SteamVR_Action_Single rightTriggerAnalog;
        
        public Valve.VR.SteamVR_Action_Boolean leftDpadTouch;
        
        public Valve.VR.SteamVR_Action_Boolean rightDpadTouch;
        
        public Valve.VR.SteamVR_Action_Vector2 leftDpadPosition;
        
        public Valve.VR.SteamVR_Action_Vector2 rightDpadPosition;
        
        public Valve.VR.SteamVR_Action_Pose leftPose;
        
        public Valve.VR.SteamVR_Action_Pose rightPose;
    }
}
