// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace Valve.VR
{
    using System;
    using UnityEngine;
    
    
    public partial class SteamVR_Input
    {
        
        public static SteamVR_Action_Vector2 __actions_platformer_in_Move;
        
        public static SteamVR_Action_Boolean __actions_platformer_in_Jump;
        
        public static SteamVR_Action_Vector2 __actions_buggy_in_Steering;
        
        public static SteamVR_Action_Single __actions_buggy_in_Throttle;
        
        public static SteamVR_Action_Boolean __actions_buggy_in_Brake;
        
        public static SteamVR_Action_Boolean __actions_buggy_in_Reset;
        
        public static SteamVR_Action_Boolean __actions_Buttons_Input_in_leftTrigger;
        
        public static SteamVR_Action_Boolean __actions_Buttons_Input_in_rightTrigger;
        
        public static SteamVR_Action_Boolean __actions_Buttons_Input_in_leftMenuButton;
        
        public static SteamVR_Action_Boolean __actions_Buttons_Input_in_rightMenuButton;
        
        public static SteamVR_Action_Boolean __actions_Buttons_Input_in_leftDpad;
        
        public static SteamVR_Action_Boolean __actions_Buttons_Input_in_rightDpad;
        
        public static SteamVR_Action_Boolean __actions_Buttons_Input_in_leftSystemButton;
        
        public static SteamVR_Action_Boolean __actions_Buttons_Input_in_rightSystemButton;
        
        public static SteamVR_Action_Boolean __actions_Buttons_Input_in_leftGrip;
        
        public static SteamVR_Action_Boolean __actions_Buttons_Input_in_rightGrip;
        
        public static SteamVR_Action_Vibration __actions_Buttons_Input_out_leftVibration;
        
        public static SteamVR_Action_Vibration __actions_Buttons_Input_out_rightVibration;
        
        public static void Dynamic_InitializeActions()
        {
            SteamVR_Input.__actions_platformer_in_Move.Initialize();
            SteamVR_Input.__actions_platformer_in_Jump.Initialize();
            SteamVR_Input.__actions_buggy_in_Steering.Initialize();
            SteamVR_Input.__actions_buggy_in_Throttle.Initialize();
            SteamVR_Input.__actions_buggy_in_Brake.Initialize();
            SteamVR_Input.__actions_buggy_in_Reset.Initialize();
            SteamVR_Input.__actions_Buttons_Input_in_leftTrigger.Initialize();
            SteamVR_Input.__actions_Buttons_Input_in_rightTrigger.Initialize();
            SteamVR_Input.__actions_Buttons_Input_in_leftMenuButton.Initialize();
            SteamVR_Input.__actions_Buttons_Input_in_rightMenuButton.Initialize();
            SteamVR_Input.__actions_Buttons_Input_in_leftDpad.Initialize();
            SteamVR_Input.__actions_Buttons_Input_in_rightDpad.Initialize();
            SteamVR_Input.__actions_Buttons_Input_in_leftSystemButton.Initialize();
            SteamVR_Input.__actions_Buttons_Input_in_rightSystemButton.Initialize();
            SteamVR_Input.__actions_Buttons_Input_in_leftGrip.Initialize();
            SteamVR_Input.__actions_Buttons_Input_in_rightGrip.Initialize();
            SteamVR_Input.__actions_Buttons_Input_out_leftVibration.Initialize();
            SteamVR_Input.__actions_Buttons_Input_out_rightVibration.Initialize();
        }
        
        public static void Dynamic_InitializeInstanceActions()
        {
            Valve.VR.SteamVR_Input.__actions_platformer_in_Move = ((SteamVR_Action_Vector2)(SteamVR_Input_References.GetAction("__actions_platformer_in_Move")));
            Valve.VR.SteamVR_Input.__actions_platformer_in_Jump = ((SteamVR_Action_Boolean)(SteamVR_Input_References.GetAction("__actions_platformer_in_Jump")));
            Valve.VR.SteamVR_Input.__actions_buggy_in_Steering = ((SteamVR_Action_Vector2)(SteamVR_Input_References.GetAction("__actions_buggy_in_Steering")));
            Valve.VR.SteamVR_Input.__actions_buggy_in_Throttle = ((SteamVR_Action_Single)(SteamVR_Input_References.GetAction("__actions_buggy_in_Throttle")));
            Valve.VR.SteamVR_Input.__actions_buggy_in_Brake = ((SteamVR_Action_Boolean)(SteamVR_Input_References.GetAction("__actions_buggy_in_Brake")));
            Valve.VR.SteamVR_Input.__actions_buggy_in_Reset = ((SteamVR_Action_Boolean)(SteamVR_Input_References.GetAction("__actions_buggy_in_Reset")));
            Valve.VR.SteamVR_Input.__actions_Buttons_Input_in_leftTrigger = ((SteamVR_Action_Boolean)(SteamVR_Input_References.GetAction("__actions_Buttons_Input_in_leftTrigger")));
            Valve.VR.SteamVR_Input.__actions_Buttons_Input_in_rightTrigger = ((SteamVR_Action_Boolean)(SteamVR_Input_References.GetAction("__actions_Buttons_Input_in_rightTrigger")));
            Valve.VR.SteamVR_Input.__actions_Buttons_Input_in_leftMenuButton = ((SteamVR_Action_Boolean)(SteamVR_Input_References.GetAction("__actions_Buttons_Input_in_leftMenuButton")));
            Valve.VR.SteamVR_Input.__actions_Buttons_Input_in_rightMenuButton = ((SteamVR_Action_Boolean)(SteamVR_Input_References.GetAction("__actions_Buttons_Input_in_rightMenuButton")));
            Valve.VR.SteamVR_Input.__actions_Buttons_Input_in_leftDpad = ((SteamVR_Action_Boolean)(SteamVR_Input_References.GetAction("__actions_Buttons_Input_in_leftDpad")));
            Valve.VR.SteamVR_Input.__actions_Buttons_Input_in_rightDpad = ((SteamVR_Action_Boolean)(SteamVR_Input_References.GetAction("__actions_Buttons_Input_in_rightDpad")));
            Valve.VR.SteamVR_Input.__actions_Buttons_Input_in_leftSystemButton = ((SteamVR_Action_Boolean)(SteamVR_Input_References.GetAction("__actions_Buttons_Input_in_leftSystemButton")));
            Valve.VR.SteamVR_Input.__actions_Buttons_Input_in_rightSystemButton = ((SteamVR_Action_Boolean)(SteamVR_Input_References.GetAction("__actions_Buttons_Input_in_rightSystemButton")));
            Valve.VR.SteamVR_Input.__actions_Buttons_Input_in_leftGrip = ((SteamVR_Action_Boolean)(SteamVR_Input_References.GetAction("__actions_Buttons_Input_in_leftGrip")));
            Valve.VR.SteamVR_Input.__actions_Buttons_Input_in_rightGrip = ((SteamVR_Action_Boolean)(SteamVR_Input_References.GetAction("__actions_Buttons_Input_in_rightGrip")));
            Valve.VR.SteamVR_Input.__actions_Buttons_Input_out_leftVibration = ((SteamVR_Action_Vibration)(SteamVR_Input_References.GetAction("__actions_Buttons_Input_out_leftVibration")));
            Valve.VR.SteamVR_Input.__actions_Buttons_Input_out_rightVibration = ((SteamVR_Action_Vibration)(SteamVR_Input_References.GetAction("__actions_Buttons_Input_out_rightVibration")));
            Valve.VR.SteamVR_Input.actions = new Valve.VR.SteamVR_Action[]
            {
                    Valve.VR.SteamVR_Input.__actions_platformer_in_Move,
                    Valve.VR.SteamVR_Input.__actions_platformer_in_Jump,
                    Valve.VR.SteamVR_Input.__actions_buggy_in_Steering,
                    Valve.VR.SteamVR_Input.__actions_buggy_in_Throttle,
                    Valve.VR.SteamVR_Input.__actions_buggy_in_Brake,
                    Valve.VR.SteamVR_Input.__actions_buggy_in_Reset,
                    Valve.VR.SteamVR_Input.__actions_Buttons_Input_in_leftTrigger,
                    Valve.VR.SteamVR_Input.__actions_Buttons_Input_in_rightTrigger,
                    Valve.VR.SteamVR_Input.__actions_Buttons_Input_in_leftMenuButton,
                    Valve.VR.SteamVR_Input.__actions_Buttons_Input_in_rightMenuButton,
                    Valve.VR.SteamVR_Input.__actions_Buttons_Input_in_leftDpad,
                    Valve.VR.SteamVR_Input.__actions_Buttons_Input_in_rightDpad,
                    Valve.VR.SteamVR_Input.__actions_Buttons_Input_in_leftSystemButton,
                    Valve.VR.SteamVR_Input.__actions_Buttons_Input_in_rightSystemButton,
                    Valve.VR.SteamVR_Input.__actions_Buttons_Input_in_leftGrip,
                    Valve.VR.SteamVR_Input.__actions_Buttons_Input_in_rightGrip,
                    Valve.VR.SteamVR_Input.__actions_Buttons_Input_out_leftVibration,
                    Valve.VR.SteamVR_Input.__actions_Buttons_Input_out_rightVibration};
            Valve.VR.SteamVR_Input.actionsIn = new Valve.VR.SteamVR_Action_In[]
            {
                    Valve.VR.SteamVR_Input.__actions_platformer_in_Move,
                    Valve.VR.SteamVR_Input.__actions_platformer_in_Jump,
                    Valve.VR.SteamVR_Input.__actions_buggy_in_Steering,
                    Valve.VR.SteamVR_Input.__actions_buggy_in_Throttle,
                    Valve.VR.SteamVR_Input.__actions_buggy_in_Brake,
                    Valve.VR.SteamVR_Input.__actions_buggy_in_Reset,
                    Valve.VR.SteamVR_Input.__actions_Buttons_Input_in_leftTrigger,
                    Valve.VR.SteamVR_Input.__actions_Buttons_Input_in_rightTrigger,
                    Valve.VR.SteamVR_Input.__actions_Buttons_Input_in_leftMenuButton,
                    Valve.VR.SteamVR_Input.__actions_Buttons_Input_in_rightMenuButton,
                    Valve.VR.SteamVR_Input.__actions_Buttons_Input_in_leftDpad,
                    Valve.VR.SteamVR_Input.__actions_Buttons_Input_in_rightDpad,
                    Valve.VR.SteamVR_Input.__actions_Buttons_Input_in_leftSystemButton,
                    Valve.VR.SteamVR_Input.__actions_Buttons_Input_in_rightSystemButton,
                    Valve.VR.SteamVR_Input.__actions_Buttons_Input_in_leftGrip,
                    Valve.VR.SteamVR_Input.__actions_Buttons_Input_in_rightGrip};
            Valve.VR.SteamVR_Input.actionsOut = new Valve.VR.SteamVR_Action_Out[]
            {
                    Valve.VR.SteamVR_Input.__actions_Buttons_Input_out_leftVibration,
                    Valve.VR.SteamVR_Input.__actions_Buttons_Input_out_rightVibration};
            Valve.VR.SteamVR_Input.actionsVibration = new Valve.VR.SteamVR_Action_Vibration[]
            {
                    Valve.VR.SteamVR_Input.__actions_Buttons_Input_out_leftVibration,
                    Valve.VR.SteamVR_Input.__actions_Buttons_Input_out_rightVibration};
            Valve.VR.SteamVR_Input.actionsPose = new Valve.VR.SteamVR_Action_Pose[0];
            Valve.VR.SteamVR_Input.actionsBoolean = new Valve.VR.SteamVR_Action_Boolean[]
            {
                    Valve.VR.SteamVR_Input.__actions_platformer_in_Jump,
                    Valve.VR.SteamVR_Input.__actions_buggy_in_Brake,
                    Valve.VR.SteamVR_Input.__actions_buggy_in_Reset,
                    Valve.VR.SteamVR_Input.__actions_Buttons_Input_in_leftTrigger,
                    Valve.VR.SteamVR_Input.__actions_Buttons_Input_in_rightTrigger,
                    Valve.VR.SteamVR_Input.__actions_Buttons_Input_in_leftMenuButton,
                    Valve.VR.SteamVR_Input.__actions_Buttons_Input_in_rightMenuButton,
                    Valve.VR.SteamVR_Input.__actions_Buttons_Input_in_leftDpad,
                    Valve.VR.SteamVR_Input.__actions_Buttons_Input_in_rightDpad,
                    Valve.VR.SteamVR_Input.__actions_Buttons_Input_in_leftSystemButton,
                    Valve.VR.SteamVR_Input.__actions_Buttons_Input_in_rightSystemButton,
                    Valve.VR.SteamVR_Input.__actions_Buttons_Input_in_leftGrip,
                    Valve.VR.SteamVR_Input.__actions_Buttons_Input_in_rightGrip};
            Valve.VR.SteamVR_Input.actionsSingle = new Valve.VR.SteamVR_Action_Single[]
            {
                    Valve.VR.SteamVR_Input.__actions_buggy_in_Throttle};
            Valve.VR.SteamVR_Input.actionsVector2 = new Valve.VR.SteamVR_Action_Vector2[]
            {
                    Valve.VR.SteamVR_Input.__actions_platformer_in_Move,
                    Valve.VR.SteamVR_Input.__actions_buggy_in_Steering};
            Valve.VR.SteamVR_Input.actionsVector3 = new Valve.VR.SteamVR_Action_Vector3[0];
            Valve.VR.SteamVR_Input.actionsSkeleton = new Valve.VR.SteamVR_Action_Skeleton[0];
            Valve.VR.SteamVR_Input.actionsNonPoseNonSkeletonIn = new Valve.VR.SteamVR_Action_In[]
            {
                    Valve.VR.SteamVR_Input.__actions_platformer_in_Move,
                    Valve.VR.SteamVR_Input.__actions_platformer_in_Jump,
                    Valve.VR.SteamVR_Input.__actions_buggy_in_Steering,
                    Valve.VR.SteamVR_Input.__actions_buggy_in_Throttle,
                    Valve.VR.SteamVR_Input.__actions_buggy_in_Brake,
                    Valve.VR.SteamVR_Input.__actions_buggy_in_Reset,
                    Valve.VR.SteamVR_Input.__actions_Buttons_Input_in_leftTrigger,
                    Valve.VR.SteamVR_Input.__actions_Buttons_Input_in_rightTrigger,
                    Valve.VR.SteamVR_Input.__actions_Buttons_Input_in_leftMenuButton,
                    Valve.VR.SteamVR_Input.__actions_Buttons_Input_in_rightMenuButton,
                    Valve.VR.SteamVR_Input.__actions_Buttons_Input_in_leftDpad,
                    Valve.VR.SteamVR_Input.__actions_Buttons_Input_in_rightDpad,
                    Valve.VR.SteamVR_Input.__actions_Buttons_Input_in_leftSystemButton,
                    Valve.VR.SteamVR_Input.__actions_Buttons_Input_in_rightSystemButton,
                    Valve.VR.SteamVR_Input.__actions_Buttons_Input_in_leftGrip,
                    Valve.VR.SteamVR_Input.__actions_Buttons_Input_in_rightGrip};
        }
    }
}
